### PR TITLE
Feat/sdk docs

### PR DESCRIPTION
**Pull request by bmunday3**
The two pages for your review are created with `docs/docs/chassisml-sdk-reference.md` and `docs/docs/service-reference.md`, but **NOTE**: these are just the "home pages" where you can write any markdown you want in there, but also have the ability to point to a specific module containing docstrings to auto-generate the class and method-specific docs. You'll notice both files contain some intro/subtitles text and then point to `chassisml-sdk/chassisml/chassisml.py` module and `service/app.py`, respectively. [Here ](https://mkdocstrings.github.io/handlers/python/#google-style)is the mkdocstrings support I used for formatting.

### CODE REVIEW

**Comment by DataScienceDeconstructed** [comment]
per @bmunday3  this resolves #54

**Comment by DataScienceDeconstructed** [comment]
I think this is a good start but I think we should settle on a consistent documentation scheme. some of the methods have Parameters, Returns, Examples and some have a subset of that. 

I would recommend that all methods for the service and the SDK have Parameters and Returns and the SDK also include an Example.

**Comment by bmunday3** [comment]
Agreed that makes sense. I think the only methods that don't adhere to the Params, Returns, Examples scheme are the methods that don't actually return anything, so we just need to decide how we want to document those methods' "returns" section...maybe it's just "None"?

**Comment by DataScienceDeconstructed** [comment]
reviewed the new additions and all looks good to me. thanks @bmunday3

**Pull request merged**
